(() => {
  'use strict';
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  let panel = null, activeTab = 'friends';
  const get = async url => fetch(url, { credentials: 'same-origin' }).then(response => response.json());
  const post = async (url, body) => fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify(body) }).then(response => response.json());
  function styles() { if (document.getElementById('idk-friends-style')) return; const link = document.createElement('link'); link.id = 'idk-friends-style'; link.rel = 'stylesheet'; link.href = 'idk-friends.css?v=2'; document.head.append(link); }
  function userRow(user, add) { const row = document.createElement('div'); row.className = 'idk-friend-row'; const initial = esc((user.username || '?').slice(0, 1).toUpperCase()); row.innerHTML = `<span class="idk-friend-avatar">${user.avatar ? `<img class="idk-friend-avatar" src="${esc(user.avatar)}" alt="">` : initial}</span><span class="idk-friend-info"><strong>${esc(user.username)}</strong><small>${add ? 'IDK user' : 'Friend'}</small></span><button type="button" class="idk-friend-action">${add ? 'Add' : 'Chat'}</button>`; const action = row.querySelector('.idk-friend-action'); if (add) action.onclick = async () => { action.disabled = true; const result = await post('/api/friends/request', { username: user.username }).catch(() => ({ ok: false, error: 'Could not reach the Friends service.' })); const error = panel?.querySelector('.idk-friend-error'); if (result.ok) { action.textContent = 'Sent'; if (error) error.textContent = `Friend request sent to ${user.username}.`; } else { action.disabled = false; if (error) error.textContent = result.error || 'Could not send request.'; } }; else action.onclick = () => startChat(user); return row; }
  function updateBadges(data) { const incoming = data?.incoming?.length || 0; const badge = panel?.querySelector('[data-request-badge]'); if (badge) { badge.textContent = String(incoming); badge.hidden = incoming === 0; } const tab = panel?.querySelector('[data-friend-tab="requests"]'); if (tab) tab.setAttribute('aria-label', `Requests${incoming ? `, ${incoming} pending` : ''}`); }
  async function search(query) { if (!panel) return; const list = panel.querySelector('.idk-friends-list'), error = panel.querySelector('.idk-friend-error'); if (query.length < 2) { error.textContent = 'Type at least 2 characters to search.'; list.replaceChildren(); return; } error.textContent = ''; list.innerHTML = '<div class="idk-friend-empty">Searching…</div>'; try { const result = await get(`/api/friends/search?q=${encodeURIComponent(query)}`); if (!result.ok) { error.textContent = result.error || 'Search failed.'; return; } list.replaceChildren(); if (!result.users?.length) list.append(Object.assign(document.createElement('div'), { className: 'idk-friend-empty', textContent: 'No users found. Try another username.' })); else result.users.forEach(user => list.append(userRow(user, true))); } catch { error.textContent = 'Could not reach the Friends service.'; } }
  async function load() { if (!panel) return; const list = panel.querySelector('.idk-friends-list'), error = panel.querySelector('.idk-friend-error'); error.textContent = ''; list.innerHTML = '<div class="idk-friend-empty">Loading…</div>'; try { const result = await get('/api/friends'); updateBadges(result); if (!result.ok) { error.textContent = result.error || 'Could not load Friends.'; return; } list.replaceChildren(); if (activeTab === 'friends') { if (!result.friends?.length) list.append(Object.assign(document.createElement('div'), { className: 'idk-friend-empty', textContent: 'No friends yet. Search for someone above to add them.' })); else result.friends.forEach(user => list.append(userRow(user, false))); } else if (activeTab === 'requests') { if (!result.incoming?.length) list.append(Object.assign(document.createElement('div'), { className: 'idk-friend-empty', textContent: 'No new friend requests.' })); else result.incoming.forEach(request => { const row = userRow({ id: request.userId, username: request.username, avatar: request.avatar }, false); row.querySelector('small').textContent = 'Wants to be your friend'; const accept = row.querySelector('.idk-friend-action'); accept.textContent = 'Accept'; accept.onclick = async () => { accept.disabled = true; const response = await post('/api/friends/respond', { requestId: request.id, action: 'accept' }); if (response.ok) load(); else { accept.disabled = false; error.textContent = response.error || 'Could not accept request.'; } }; const decline = document.createElement('button'); decline.type = 'button'; decline.className = 'idk-friend-action'; decline.textContent = 'Decline'; decline.onclick = async () => { const response = await post('/api/friends/respond', { requestId: request.id, action: 'decline' }); if (response.ok) load(); else error.textContent = response.error || 'Could not decline request.'; }; row.append(decline); list.append(row); }); } else { if (!result.outgoing?.length) list.append(Object.assign(document.createElement('div'), { className: 'idk-friend-empty', textContent: 'No outgoing requests.' })); else result.outgoing.forEach(request => { const row = userRow({ username: request.username, avatar: request.avatar }, false); row.querySelector('small').textContent = 'Request pending'; const action = row.querySelector('.idk-friend-action'); action.textContent = 'Pending'; action.disabled = true; list.append(row); }); } } catch { error.textContent = 'Could not reach the Friends service.'; } }
  function startChat(user) { panel?.remove(); panel = null; document.querySelector('.idk-friends-button')?.remove(); window.IdkMessenger?.open?.(); window.IdkMessenger?.selectUser?.({ userId: user.id || user.userId, username: user.username }); }
  function open() { styles(); const messenger = document.querySelector('.idk-live-messenger'); if (!messenger) return window.IdkMessenger?.open?.(); panel?.remove(); const button = document.createElement('button'); button.type = 'button'; button.className = 'idk-friends-button'; button.innerHTML = '👥 Friends <b data-request-badge hidden>0</b>'; messenger.querySelector('.idk-live-title')?.append(button); panel = document.createElement('section'); panel.className = 'idk-friends-panel'; panel.innerHTML = '<div class="idk-friends-head"><div><strong>Friends</strong><small>Find people, connect, and start a private chat.</small></div><button type="button" class="idk-friends-close" aria-label="Close Friends">×</button></div><form class="idk-friends-search"><input class="field" maxlength="32" placeholder="Search IDK users…" autocomplete="off"><button type="submit">Search</button></form><div class="idk-friend-error" role="status"></div><nav class="idk-friends-tabs"><button type="button" data-friend-tab="friends" class="active">Friends</button><button type="button" data-friend-tab="requests">Requests</button><button type="button" data-friend-tab="outgoing">Sent</button></nav><div class="idk-friends-list"></div>'; button.onclick = () => { panel.hidden = !panel.hidden; if (!panel.hidden) load(); }; messenger.append(panel); panel.querySelector('.idk-friends-close').onclick = () => { panel.remove(); panel = null; button.remove(); }; panel.querySelectorAll('[data-friend-tab]').forEach(tab => tab.onclick = () => { activeTab = tab.dataset.friendTab; panel.querySelectorAll('[data-friend-tab]').forEach(item => item.classList.toggle('active', item === tab)); load(); }); panel.querySelector('form').onsubmit = event => { event.preventDefault(); search(panel.querySelector('input').value.trim()); }; load(); }
  function attach() { if (document.querySelector('.idk-live-messenger') && !document.querySelector('.idk-friends-button')) open(); }
  const observer = new MutationObserver(attach); function init() { observer.observe(document.body, { childList: true, subtree: true }); attach(); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, { once: true }); else init();
  window.IdkFriends = { open, load };
})();
